spring:
  application:
    name: spring-zuul
  zipkin:
      base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8086
server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: spring-cloud-ribbon
    api-b:
      path: /api/b/**
      serviceId: spring-cloud-feign







