spring:
  application:
    name: spring-zipkin
  boot:
    admin:
      client:
        url: http://localhost:8086
server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
management:
  metrics:
    web:
      server:
        auto-time-requests: false