spring:
  application:
    name: spring-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/wjwujun/spring-cloud-config.git
          search-paths: respo
          username:
          password:
  zipkin:
      base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8086

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}

